# Generated by Django 3.1.4 on 2021-01-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='contact_icon',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
