# Generated by Django 3.1.4 on 2021-01-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0002_auto_20210101_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='contact_url',
            field=models.URLField(default='#'),
        ),
    ]
