# Generated by Django 3.1.4 on 2021-01-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0003_contactdetails_contact_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='contact_url',
            field=models.URLField(default='#', null=True),
        ),
    ]
