# Generated by Django 3.1.4 on 2021-01-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0004_auto_20210103_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='contact_url',
            field=models.URLField(blank=True, default='#'),
        ),
    ]
