# Generated by Django 3.1.4 on 2021-01-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Education Model',
                'verbose_name_plural': 'Education Model',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Job Model',
                'verbose_name_plural': 'Job Model',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Language Model',
                'verbose_name_plural': 'Language Model',
            },
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_title', models.CharField(max_length=100)),
                ('publication_year', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Publication Model',
                'verbose_name_plural': 'Publication Model',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Volunteer Model',
                'verbose_name_plural': 'Volunteer Model',
            },
        ),
    ]
