# Generated by Django 3.1.4 on 2021-01-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=50)),
                ('institution_level', models.CharField(choices=[('Senior High School', 'Senior High School'), ('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate')], max_length=100)),
                ('graduation_date', models.DateField()),
                ('grade', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.RenameModel(
            old_name='ResumeModel',
            new_name='Volunteer',
        ),
    ]
