# Generated by Django 3.1.4 on 2021-01-05 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0003_education_institution_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Education Model'},
        ),
    ]
