# Generated by Django 3.1.4 on 2021-01-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0003_auto_20210106_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='publications',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='description',
            field=models.TextField(),
        ),
    ]
