# Generated by Django 3.1.4 on 2021-01-05 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0004_auto_20210105_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Education Model', 'verbose_name_plural': 'Education Model'},
        ),
    ]
