# Generated by Django 3.1.4 on 2021-01-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0004_auto_20210106_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='publication_year',
            field=models.DateField(),
        ),
    ]
