# Generated by Django 3.1.4 on 2021-01-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0005_auto_20210106_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
