# Generated by Django 3.1.4 on 2021-01-05 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0005_auto_20210105_2051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Volunteer',
        ),
        migrations.AlterModelOptions(
            name='jobs',
            options={'verbose_name': 'Jobs Model', 'verbose_name_plural': 'Job Model'},
        ),
    ]
