# Generated by Django 3.1.4 on 2021-01-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0006_auto_20210105_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_organization', models.CharField(max_length=100)),
                ('year', models.DateField()),
            ],
            options={
                'verbose_name': 'Volunteer Model',
                'verbose_name_plural': 'Volunteer Model',
            },
        ),
    ]
