# Generated by Django 3.1.4 on 2021-01-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0006_auto_20210106_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='finish_date',
            field=models.DateField(blank=True, default=None, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True),
            preserve_default=False,
        ),
    ]
