# Generated by Django 3.1.5 on 2021-01-10 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0007_auto_20210107_1415'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empty',
        ),
    ]
