# Generated by Django 3.1.4 on 2021-01-06 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0008_languages_publications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Languages',
        ),
        migrations.DeleteModel(
            name='Publications',
        ),
        migrations.AlterModelOptions(
            name='education',
            options={},
        ),
        migrations.AlterModelOptions(
            name='jobs',
            options={},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={},
        ),
        migrations.RemoveField(
            model_name='education',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='education',
            name='graduation_date',
        ),
        migrations.RemoveField(
            model_name='education',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='education',
            name='institution_icon',
        ),
        migrations.RemoveField(
            model_name='education',
            name='institution_level',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='volunteer_organization',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='year',
        ),
    ]
