# Generated by Django 3.1.4 on 2021-01-08 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0002_about_ab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='ab',
        ),
    ]
